### ISSUE TITLE
Only able to read sensors from 1 processor of a total of 2

### ISSUE THREAD

**Issue by cristobal-ortega** [open-power/amester#9]
My system is a P8 S822LC model 8355-GTA server.
So, it has 10 cores per chip and 2 chips.

In my experiments, it seems that AMESTER reads only from 1 chip: when running in the first 10 cores a benchmark, power readings seem as they were idle readings.
Executions of the benchmark in the last 10 cores seem normal in terms of power consumption.
I'm reading the following power sensors:
- PWR250P0
- PWR250VCS0
- PWR250VDD0

I've used a another machine, which had 2 power sensors for processor (e.g. PWR250VCS0 and PWR250VCS1).

Attached is the beginning of the execution of AMESTER in case it's needed: [amester_init.txt](https://github.com/open-power/amester/files/1305936/amester_init.txt)

**Comment by baileysh** [comment]
start with "amesterV7_1 gui_multi_proc.tcl"
the tcl file is used to do custom setup.
I have put in the needed code to loop through Procs.

I will check this in as soon as I have some time in the examples/P9.  but it works for me on P8 as well.

could not upload tcl file,, just renamed to txt file... just rename back.
[gui_mutli_proc.txt](https://github.com/open-power/amester/files/1311867/gui_mutli_proc.txt)

**Comment by cristobal-ortega** [comment]
Still, I'm just able to read 1 chip.
The file you uploaded it's the same (except for the connection section) to the one I'm using (examples/POWER8/openpower.tcl).

Chips should appear in different "ame" sections?
In the GUI, the menu Fuctions->myopenpower_node0 has only myopenpower_node0_ame0..

**Comment by baileysh** [comment]
So the reason it is not working, AMESTER is only being told about 1 AME.
This is evident by the GUI list.

I see this on a P8 firestone system I could get access to..   It has one Processor Chip.
I need you to run this CMD.

ipmitool -H "yourBMC" -I lan -U "yourADMINuser" -P "yourPASSWORD" fru list

we are looking for "**FRU Device Description : CPU X (ID X)**"
     where X is 1 , 2 , etc.

Copy the entire output results back please.

If you only get CPU 1 filled in "PROCESSOR MODULE" , then the system thinks it is a 1 processor system.

if you get CPU 1 and 2 filled in "PROCESSOR MODULE" , then we will have to turn on higher DEBUG output.

**Comment by cristobal-ortega** [comment]
Here is the output for that command [output_fruList.txt](https://github.com/open-power/amester/files/1314608/output_fruList.txt). I can see 2 CPUS.

But, I've doing some experiments. Is it possible that the sensor names are (kind of) incomplete?

For example:
    PWR250P0 -> Power consumption for Processor 0
    PWR250VCS0 ->  VCS power consumption for Processor 0
    PWR250VDD0 -> VDD power consumption for Processor 0

In my experiments, I can almost assure that there are different sensors reporting the same statistics:
VCS0 = PWRAPSSCH5
VDD0 = PWRAPSSCH1

Also, I found that is probable that (through a power stressmark)
VCS1 = PWRAPSSCH6
VDD1 = PWRAPSSCH2

Yet, there are no references to Processor 1 in the list of sensors (no P1, no VCS1, no VDD1, etc)
I don't know if this is known behavior, but I didn't find any documentation on this.

**Comment by baileysh** [comment]
Got it:  change from V7.0 to V7.1 to support 1 Processor Module.
I was told that the FRU LIST would populate CPU X when installed.
and not populate CPU X when not installed, but socket available.

Systems I was able to test on in P8 showed this behavior.
**_your fru list is missing "PROCESSOR MODULE"_**

YOUR FRU LIST :
  FRU Device Description : CPU 1 (ID 1)
   Board Mfg Date        : Mon Jan  1 01:00:00 1996

  FRU Device Description : CPU 2 (ID 2)
   Board Mfg Date        : Mon Jan  1 01:00:00 1996

CHANGE TO HANDLE 1 PROCESSOR SYSTEM :
look for "PROCESSOR MODULE" instead of "CPU X (ID X)"
This was needed since fru list for one processor module looks like

FRU Device Description : CPU 1 (ID 1)
 Board Mfg Date        : Sun Dec 31 18:00:00 1995
 Board Mfg             : IBM
 Board Product         : **PROCESSOR MODULE**
 Board Serial          : xxxxxxxxx
 Board Part Number     : xxxxxxx
 Board Extra           : ECID:xxxxxxxx
 Board Extra           : EC:xxxxxxxx

FRU Device Description : CPU 2 (ID 2)



Temp Fix:
/vfs/lib/app-amester/openpower.itcl
lines 310 - 313 comment out.
This will leave the CPU X count to be used.

Can you change the code, and confirm that works for you..
I will look at a change needed to make this work permanently.

**Comment by cristobal-ortega** [comment]
As you said, commenting lines 310 - 313 fixed the issue.
Thank you.

**Comment by baileysh** [comment]
Sounds good.
